// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0dUYPqFhs4AsqmPYjfIruwIJ0trMYra8',
    appId: '1:910249466722:web:fe0ae61c5459604cd0aa3b',
    messagingSenderId: '910249466722',
    projectId: 'proyekmmp-58353',
    authDomain: 'proyekmmp-58353.firebaseapp.com',
    storageBucket: 'proyekmmp-58353.firebasestorage.app',
    measurementId: 'G-DB440Y8NY1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgsuyy_PHo7fGictIqOKChVOVzNEHRNBs',
    appId: '1:910249466722:ios:78dee3fefd1372dad0aa3b',
    messagingSenderId: '910249466722',
    projectId: 'proyekmmp-58353',
    storageBucket: 'proyekmmp-58353.firebasestorage.app',
    iosBundleId: 'com.example.cityCare',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnvdXoHe3BcnvOKHGAfI1FCuEocDqb2NQ',
    appId: '1:910249466722:android:117259f1fb826472d0aa3b',
    messagingSenderId: '910249466722',
    projectId: 'proyekmmp-58353',
    storageBucket: 'proyekmmp-58353.firebasestorage.app',
  );

}